DROP TABLE IF EXISTS reserve;
DROP TABLE IF EXISTS passePar;
DROP TABLE IF EXISTS appartient;
DROP TABLE IF EXISTS tache;
DROP TABLE IF EXISTS personne;
DROP TABLE IF EXISTS piece;
DROP USER grtt42;
DROP USER grtt1;