DROP VIEW rapport_activite;
DROP VIEW intrusion;
DROP TRIGGER triggerAppartient ON appartient;
DROP TRIGGER triggerReservation ON reservation;
DROP TABLE IF EXISTS reservation;
DROP TABLE IF EXISTS passePar;
DROP TABLE IF EXISTS appartient;
DROP TABLE IF EXISTS tache;
DROP TABLE IF EXISTS personne;
DROP TABLE IF EXISTS piece;
DROP FUNCTION tacheCoherente(DATE,VARCHAR(10));
DROP FUNCTION estIntru(DATE, VARCHAR(10), VARCHAR(10));
DROP FUNCTION testAppartient();
DROP FUNCTION testReservation();