#!/bin/bash
# Utilisation : ./compile fichiersansextension
echo "ECPG"
ecpg $1
echo "Compilation"
gcc -g -Wall  -c -I/usr/include/postgresql $1.c
echo "Édition des liens"
gcc -o $1 $1.o -L/usr/lib -lpq -lpgtypes -lecpg 